# Generated by Django 4.0.4 on 2022-05-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id_deuda', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id deuda')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre deuda')),
                ('Cantidad', models.IntegerField(verbose_name='Cantidad deuda')),
                ('foto', models.ImageField(upload_to='Catalogo')),
                ('descripcion', models.TextField(verbose_name='Descripcion deuda')),
                ('url', models.URLField(verbose_name='Url video')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRol', models.CharField(max_length=40, verbose_name='Nombre rol')),
                ('tipoRol', models.CharField(max_length=20, verbose_name='Nombre de rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de usuario')),
                ('nombreUsuario', models.CharField(max_length=30, verbose_name='Nombre usuario')),
                ('apellidoUsuario', models.CharField(max_length=40, verbose_name='Apellido usuario')),
                ('correo', models.CharField(max_length=30, verbose_name='Correo')),
                ('clave', models.CharField(max_length=30, verbose_name='Clave'))
            ],
        ),
    ]
